apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - gateway/configmap.yaml
  - gateway/secret.yaml
  - gateway/deployment.yaml
  - gateway/service.yaml
  - gateway/service-lb.yaml
  - gateway/ingress.yaml
  - gateway/hpa.yaml
  - redis/deployment.yaml
  - redis/service.yaml
