apiVersion: v1
kind: Service
metadata:
  name: nexus-gateway-lb
  namespace: nexus
spec:
  type: LoadBalancer
  selector:
    app: nexus-gateway
  ports:
    - name: http
      port: 80
      targetPort: 8000
