apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexus-gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nohdol97/Nexus.git
    targetRevision: main
    path: k8s/overlays/mock
  destination:
    server: https://kubernetes.default.svc
    namespace: nexus
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
